service: serverless-local
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    TABLE_NAME: local-users
    SES_EMAIL: no-reply@duckfarm.com
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - ses:SendEmail
          Resource: "*"

plugins:
  - serverless-localstack
  # - serverless-offline

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

functions:
  notifier:
    handler: handler.email
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - UsersTable
              - StreamArn

# to reduce bundling files into lambda
package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!node_modules/**'
    - '!**/*.test.js'
    - '!**/__tests__/**'
    - '!package-lock.json'


resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: local-users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE

